# Generated by tf-migrate 2.0.0-beta1


component "terraform_module" {
  source = "./terraform_modules"

  inputs = {
    "aws_region"      = var.aws_region
    "private_subnets" = var.private_subnets
    "public_subnets"  = var.public_subnets
    "vpc_cidr"        = var.vpc_cidr
    "vpc_name"        = var.vpc_name
  }


  providers = {
    aws = provider.aws.this
    tls = provider.tls.this
  }
}


