# Generated by tf-migrate 2.0.0-beta1



# Note on stacks authentication:
# tf-migrate cannot generate stack authentication, this needs to be manually added before execute
# More on authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate

store "varset" "credentials" {
  name     = "Robin AWS Credentials"
  category = "env"
}

deployment "learn-terraform-stacks-migrate-robin" {
  inputs = {
    access_key    = store.varset.credentials.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.credentials.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.credentials.AWS_SESSION_TOKEN
    
    vpc_cidr        = "10.0.0.0/16"
    private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
    public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
    aws_region      = "us-east-1"
    vpc_name        = "learn-stacks-vpc"
  }
}



