# Generated by tf-migrate 2.0.0-beta1


output "intance_ids" {
  description = "EC2 instance IDs"
  value       = component.terraform_module.intance_ids
  type        = tuple([string, string, string])
}

output "intance_private_dns" {
  description = "EC2 instance Private DNS names"
  value       = component.terraform_module.intance_private_dns
  type        = tuple([string, string, string])
}

