# Generated by tf-migrate 2.0.0-beta1



provider "aws" "this" {
  config {
    region = var.aws_region

    access_key = var.access_key
    secret_key = var.secret_key
    token      = var.session_token    
  }
}

required_providers {
  aws = {
    source  = "hashicorp/aws"
    version = ">= 6.0.0, ~> 6.18.0"
  }
  tls = {
    source  = "hashicorp/tls"
    version = "~> 4.1.0"
  }
}
provider "tls" "this" {
}
